version: "3.9"
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth
    stdin_open: true
    image: hink_auth
    volumes:
      - .:/usr/src/app
    environment:
      - CONSUL_URL=consul:8500
      - CONSUL_PATH=auth
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
    networks:
      - hink-general

  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    tty: true
    hostname: mysql
    stdin_open: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hink-general

  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - cache_data:/data
    networks:
      - hink-general

  consul:
    container_name: consul
    image: consul:latest
    restart: unless-stopped
    tty: true
    hostname: consul
    stdin_open: true
    ports:
      - 8500:8500
    networks:
      - hink-general

volumes:
  mysql_data:
  cache_data:

networks:
  hink-general:
    external: true