package errutil

import (
	"errors"
)

var (
	ErrInvalidEmail                     = errors.New("invalid email")
	ErrInvalidPassword                  = errors.New("invalid password")
	ErrCreateJwt                        = errors.New("failed to create JWT token")
	ErrAccessTokenSign                  = errors.New("failed to sign access_token")
	ErrRefreshTokenSign                 = errors.New("failed to sign refresh_token")
	ErrStoreTokenUuid                   = errors.New("failed to store token uuid")
	ErrUpdateMetaData                   = errors.New("failed to update metadata")
	ErrNoContextUser                    = errors.New("failed to get user from context")
	ErrInvalidRefreshToken              = errors.New("invalid refresh_token")
	ErrInvalidAccessToken               = errors.New("invalid access_token")
	ErrInvalidPasswordResetToken        = errors.New("invalid reset_token")
	ErrInvalidRefreshUuid               = errors.New("invalid refresh_uuid")
	ErrInvalidAccessUuid                = errors.New("invalid refresh_uuid")
	ErrInvalidJwtSigningMethod          = errors.New("invalid signing method while parsing jwt")
	ErrParseJwt                         = errors.New("failed to parse JWT token")
	ErrDeleteOldTokenUuid               = errors.New("failed to delete old token uuids")
	ErrRecordNotFound                   = errors.New("record not found")
	ErrSendingEmail                     = errors.New("failed to send email")
	ErrUserCreate                       = errors.New("failed to create user")
	ErrUserUpdate                       = errors.New("failed to update user")
	ErrInvalidOtpNonce                  = errors.New("invalid otp nonce")
	ErrInvalidOtp                       = errors.New("invalid otp")
	ErrInvalidAuNumber                  = errors.New("not an australian number")
	ErrEmailUpdateNotAllowed            = errors.New("email update not allowed")
	ErrUserNameUpdateNotAllowed         = errors.New("username update not allowed")
	ErrPasswordUpdateNotAllowed         = errors.New("password update not allowed")
	ErrPhoneNumberUpdateNotAllowed      = errors.New("phone number update not allowed")
	ErrInvalidLoginProvider             = errors.New("invalid login provider")
	ErrEmailAlreadyRegistered           = errors.New("email is already taken")
	ErrUserNameAlreadyRegistered        = errors.New("username is already taken")
	ErrUserAlreadyRegisteredViaGoogle   = errors.New("user already registered via google")
	ErrUserAlreadyRegisteredViaFacebook = errors.New("user already registered via facebook")
	ErrUserAlreadyRegisteredViaApple    = errors.New("user already registered via apple")
	ErrLoginAttemptWithAppleProvider    = errors.New("invalid login attempt")
	ErrLoginAttemptWithGoogleProvider   = errors.New("invalid login attempt")
	ErrLoginAttemptWithFacebookProvider = errors.New("invalid login attempt")
	ErrInvalidLoginToken                = errors.New("invalid social login token")
	ErrInvalidPasswordFormat            = errors.New("minimum 8 characters with at least 1 uppercase letter(A-Z), 1 lowercase letter(a-z), 1 number(0-9) and 1 special character(.!@#~$%^&*()+|_<>)")
)
